[package]
name = "RustJni"
version = "0.1.0"
authors = ["Max Monnoroch <monnoroch@gmail.com>"]
build = 'build.rs'
license = "MIT"


[lib]
name = 'jni'
path = 'lib/lib.rs'

#[tests]
#name = 'tests/main.rs'

[dependencies]
libc = "0.1.7"
